/**
 * Generator `css-motion-language-v1` —— motion.css 整文件生成器（受控 Motion Language）。
 *
 * - 只理解受控 operation：opacity（enter/exit）、width（progress）、
 *   translate（token-driven，axis + distanceRef + factor）；
 * - **不提供**任意 selector / at-rule / property / raw CSS / CSS AST；
 * - 完整文件输出（含 generated header），freshness 逐字节；
 * - Token 引用（distanceRef）经 Artifact options.tokenVarPrefixes 解析为
 *   CSS var 名（输出引用形态由 mapping 决定，不硬编码 --motion-distance-*）。
 */

import { readPointer } from './json-pointer.ts';

export const MOTION_GENERATED_HEADER =
  '/* @generated by @community-go/schemas/runtime css-motion-language-v1 —— 不要手改，运行 `pnpm codegen:design` 重新生成。 */';

/** 文档绝对指针前缀；生成器收到 source 节点（/x-community-go/source），需截去。 */
export const SOURCE_DOC_PREFIX = '/x-community-go/source';

/** 文档绝对指针 → 相对 source 节点的指针。 */
export function toSourceRelativePointer(pointer: string): string {
  if (pointer.startsWith(`${SOURCE_DOC_PREFIX}/`)) {
    return pointer.slice(SOURCE_DOC_PREFIX.length);
  }
  return pointer;
}

export type MotionOperation = Readonly<{
  op: 'opacity' | 'width' | 'translate';
  value?: number;
  axis?: 'x' | 'y';
  distanceRef?: string;
  factor?: number;
}>;

export type KeyframeFrame = Readonly<{
  stage: 'from' | 'to' | '0%' | '100%';
  ops: readonly MotionOperation[];
}>;
export type KeyframeDecl = Readonly<{
  id: string;
  doc?: readonly string[];
  frames: readonly KeyframeFrame[];
}>;
export type RecipeDecl = Readonly<{
  id: string;
  semantics: string;
  consumer: string;
  reducedMotion: string;
}>;

export type MotionLanguageSource = Readonly<{
  doc?: readonly string[];
  recipes: readonly RecipeDecl[];
  keyframes: readonly KeyframeDecl[];
}>;

export type MotionLanguageOptions = Readonly<{
  tokenVarPrefixes: ReadonlyArray<{ pointerPrefix: string; varTemplate: string }>;
  topDocComment?: { style: string; indent?: number };
  keyframeCommentStyles?: Readonly<Record<string, string>>;
  keyframeDocCommentStyle?: string;
  registryComment?: { style: string; indent?: number };
}>;

export class MotionLanguageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MotionLanguageError';
  }
}

function resolveValue(source: unknown, pointer: string, context: string): unknown {
  const { found, value } = readPointer(source, toSourceRelativePointer(pointer));
  if (!found) throw new MotionLanguageError(`${context}: Source Pointer 悬空 ${pointer}`);
  return value;
}

/** source 根：{ tokens, motionLanguage }。motionLanguage 供内容，tokens 供 ref 解析。 */
function motionLanguageNode(source: unknown): Record<string, unknown> {
  const record = mustBeRecord(source, 'source');
  const node = record.motionLanguage;
  return mustBeRecord(node, 'source.motionLanguage');
}

function mustBeRecord(value: unknown, context: string): Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new MotionLanguageError(`${context}: 期望 record`);
  }
  return value as Record<string, unknown>;
}

function assertUniqueIds(items: readonly { id: string }[], kind: string): void {
  const seen = new Set<string>();
  for (const item of items) {
    if (seen.has(item.id)) throw new MotionLanguageError(`${kind} 重复 id: ${item.id}`);
    seen.add(item.id);
  }
}

/** 注释渲染（styles: single | bare-asterisk | align | inline-asterisk）。 */
export function renderCommentBlock(lines: readonly string[], style: string, indent = 0): string[] {
  const pad = ' '.repeat(indent);
  if (style === 'single') {
    return lines.map((line) => `${pad}/* ${line} */`);
  }
  if (style === 'bare-asterisk') {
    const out: string[] = [`${pad}/*`];
    for (const line of lines) out.push(`${pad} * ${line}`);
    out.push(`${pad} */`);
    return out;
  }
  if (style === 'align') {
    const out: string[] = [];
    lines.forEach((line, i) => {
      if (i === 0) out.push(`${pad}/* ${line}，`);
      else out.push(`${pad}   ${line} */`);
    });
    return out;
  }
  if (style === 'inline-asterisk') {
    const out: string[] = [];
    lines.forEach((line, i) => {
      if (i === 0) out.push(`${pad}/* ${line}`);
      else if (i === lines.length - 1) out.push(`${pad} * ${line} */`);
      else out.push(`${pad} * ${line}`);
    });
    return out;
  }
  throw new MotionLanguageError(`未知 comment style ${style}`);
}

/** 解析 distanceRef 指向的 leafKey，并按 varTemplate 规则映射为 css var 名。 */
export function resolveTokenVarName(
  source: unknown,
  options: MotionLanguageOptions,
  ref: string,
  context: string,
): string {
  const tokens = ref.split('/');
  const leafKey = tokens[tokens.length - 1] ?? '';
  // 校验 ref 目标存在（引用完整性；source 为完整 source 根节点）。
  resolveValue(source, ref, context);
  for (const prefix of options.tokenVarPrefixes) {
    if (ref.startsWith(prefix.pointerPrefix)) {
      return prefix.varTemplate.replace('{key}', leafKey);
    }
  }
  // 未命中映射前缀：不允许隐式命名（Generator 不硬编码 css var 前缀）。
  throw new MotionLanguageError(`${context}: ref 无对应 tokenVarPrefix 映射 ${ref}`);
}

function renderOperationDeclaration(
  source: unknown,
  options: MotionLanguageOptions,
  op: MotionOperation,
  indent: number,
): string {
  const pad = ' '.repeat(indent);
  switch (op.op) {
    case 'opacity': {
      const value = op.value ?? 1;
      const declaration = `opacity: ${value};`;
      return `${pad}${declaration}`;
    }
    case 'width': {
      const value = op.value ?? 0;
      return `${pad}width: ${value}%;`;
    }
    case 'translate': {
      if (!op.axis) throw new MotionLanguageError('translate 缺少 axis');
      if (!op.distanceRef) throw new MotionLanguageError('translate 缺少 distanceRef');
      const varName = resolveTokenVarName(source, options, op.distanceRef, 'translate');
      const factor = op.factor ?? 1;
      const axisUpper = op.axis === 'x' ? 'X' : 'Y';
      const cssValue =
        factor === 1
          ? `var(${varName})`
          : factor === -1
            ? `calc(var(${varName}) * -1)`
            : `calc(var(${varName}) * ${factor})`;
      return `${pad}transform: translate${axisUpper}(${cssValue});`;
    }
    default:
      throw new MotionLanguageError(`非法 operation: ${(op as { op?: string }).op}`);
  }
}

function stageLabel(stage: KeyframeFrame['stage']): string {
  return stage;
}

/** 渲染整份 motion.css（无尾随 blank 处理由调用方归一；含 generated header）。 */
export function renderMotionLanguageCss(source: unknown, options: MotionLanguageOptions): string {
  const language = motionLanguageNode(source);
  const topDoc = language.doc;
  if (!Array.isArray(topDoc)) {
    throw new MotionLanguageError('motionLanguage.doc 必须是数组');
  }
  const recipes = (language.recipes ?? []) as readonly RecipeDecl[];
  const keyframes = (language.keyframes ?? []) as readonly KeyframeDecl[];
  assertUniqueIds(recipes, 'recipe');
  assertUniqueIds(keyframes, 'keyframe');

  const lines: string[] = [];
  lines.push(MOTION_GENERATED_HEADER);
  lines.push('');

  // 1. 顶部权威说明（bare-asterisk 注释块）。
  const topStyle = options.topDocComment?.style ?? 'bare-asterisk';
  const topIndent = options.topDocComment?.indent ?? 0;
  lines.push(...renderCommentBlock((topDoc ?? []) as string[], topStyle, topIndent));

  // 2. keyframes（含 per-keyframe doc 注释）。
  const defaultKeyframeStyle = options.keyframeDocCommentStyle ?? 'bare-asterisk';
  for (const keyframe of keyframes) {
    lines.push('');
    if (keyframe.doc && keyframe.doc.length > 0) {
      const style = options.keyframeCommentStyles?.[keyframe.id] ?? defaultKeyframeStyle;
      lines.push(...renderCommentBlock(keyframe.doc, style, 0));
    }
    lines.push(`@keyframes ${keyframe.id} {`);
    for (const frame of keyframe.frames) {
      lines.push(`  ${stageLabel(frame.stage)} {`);
      for (const op of frame.ops) {
        lines.push(renderOperationDeclaration(source, options, op, 4));
      }
      lines.push('  }');
    }
    lines.push('}');
  }

  // 3. Universal recipe registry 注释块（表格）。
  const registryIndent = options.registryComment?.indent ?? 0;
  const pad = ' '.repeat(registryIndent);
  lines.push('');
  lines.push(`${pad}/*`);
  lines.push(`${pad} * Universal recipe registry`);
  lines.push(`${pad} * | recipe | 语义 | 消费方 | reduced-motion |`);
  for (const recipe of recipes) {
    lines.push(
      `${pad} * | ${recipe.id} | ${recipe.semantics} | ${recipe.consumer} | ${recipe.reducedMotion} |`,
    );
  }
  lines.push(`${pad} */`);

  return lines.join('\n');
}

/** 追加文件尾换行（与既有文件一致）。 */
export function finalizeMotionCss(content: string): string {
  return `${content}\n`;
}

/** 校验 Source 引用完整性（所有 operation ref 可解析且命中 tokenVarPrefixes）。 */
export function validateMotionLanguageReferences(
  source: unknown,
  options: MotionLanguageOptions,
): string[] {
  const issues: string[] = [];
  const language = motionLanguageNode(source);
  const keyframes = (language.keyframes ?? []) as readonly KeyframeDecl[];
  for (const keyframe of keyframes) {
    for (const frame of keyframe.frames) {
      for (const op of frame.ops) {
        if (op.op === 'translate') {
          if (!op.distanceRef) {
            issues.push(`${keyframe.id}: translate 缺少 distanceRef`);
            continue;
          }
          try {
            resolveTokenVarName(source, options, op.distanceRef, keyframe.id);
          } catch (error) {
            issues.push(String((error as Error).message));
          }
        }
      }
    }
  }
  return issues;
}

/** 渲染整份 motion.css（含 header 与尾换行）。 */
export function renderMotionCssFile(source: unknown, options: MotionLanguageOptions): string {
  const content = renderMotionLanguageCss(source, options);
  return finalizeMotionCss(content);
}
